- calliope_app/api/utils.py
Fixing error where we were using deprecated pandas ix dataframe indexer. Replaced with iloc
> Fixing deprecated ix indexer

- calliope_app/client/static/js/main.js
Fix bug where changing a parameter with a value to annual without modifying the value would cause the unconverted unit value to be written to the database
> Fix failed unit conversion

- calliope_app/client/component_views/configuration.py
Fixing bug where resampling timeseries plots would cause the request to fail and the visualization to spin. Added a temporary tzunaware index to timeseries to match input dates
> Fix pinwheel error on timeseries view resample

- calliope_app/api/fixtures/admin_run_parameter.json
- calliope_app/api/fixtures/sample_scenario_param.json
- calliope_app/client/templates/base.html
- calliope_app/client/templates/registration/login.html
- calliope_app/requirements.txt
- docs/_sources/developer-guide.rst.txt
- docs/_sources/optimization-solvers.rst.txt
- docs/_sources/release-notes.rst.txt
- docs/developer-guide.html
- docs/optimization-solvers.html
- docs/release-notes.html
- docs/sources/developer-guide.rst
- docs/sources/optimization-solvers.rst
- docs/sources/release-notes.rst
Upgrading calliope to version 0.6.7 which includes an upgrade to pyomo version 6.0. Updating all documentation links and references to use the new calliope version.
> Upgrading calliope to 0.6.7

- calliope_app/api/views/outputs.py
- calliope_app/client/templates/share.html
Fixing bug where the essential tech/loc_tech fields were not showing up as columns in CSV templates from empty models.
Also potentially fixing bug causing model sharing to fail in Firefox.
> Fixing bug in empty template CSVs

- calliope_app/account/urls.py
Adding fix to allow for larger CSRF token to prevent ReverseLookupError on password reset
See regex answers at bottom of: https://stackoverflow.com/questions/28418233/noreversematch-at-rest-auth-password-reset
> Adding fix to account for reverselookup error

- calliope_app/api/calliope_utils.py
- calliope_app/api/tasks.py
- calliope_app/api/utils.py
Refactored the YAML export code to directly write a dict during the parameter reading routines rather than write the lists and call list_to_yaml. Goal is to increase readability and flexibility to accommodate other root/dict formats
Additionally, fixed potential bug introduced with cost classes by adding parameter root to the CSV file names. Slightly refactored CSV export code to remove Exception try catch and explicitly check for Technology vs Loc_Tech when choosing CSV names.
> Refactoring YAML export code to directly write dicts

- calliope_app/compose/Dockerfile
- calliope_app/compose/run-celery-flower.sh
- calliope_app/compose/run-long-worker.sh
- calliope_app/compose/run-short-worker.sh
- calliope_app/requirements-dev.txt
- calliope_app/requirements.txt
- calliope_app/setup.py
Fix docker vulnerabilities
* Upgrade Django to version 3.2.15.
* Upgrade Celery from 4.x to 5.x
* Upgrade other related packages
* Install calliope==0.6.7 without deps, and install dependencies separately.
> Fix docker vulnerabilities

- calliope_app/api/views/outputs.py
Adding check to bulk downloads to check for empty timeseries parameters and ignore them
> Empty timeseries download fix

- calliope_app/requirements.txt
* Upgrade Django to 3.2.16
* Fix docker vulnerabilities
> Upgrade Django to 3.2.16

- calliope_app/api/calliope_utils.py
Fixing bug with unnecessary leapyear subset variable causing errors when trying to copy over timeseries files
> Fixing bug with unnecessary subset variable

- calliope_app/account/validators.py
- calliope_app/client/templates/base.html
Adjusting registration text validator to support single spaces between words in the first name, last name, and org fields
Side improvement:
Adjusting model sharing link to default to the selected model if clicked within a model context
> Adding space support back to validators

- calliope_app/client/templates/geophires_plotting.html
What's this PR
* Enable scroll on geophires plotting page, as there are four plots.
> Enable scroll on geophires plotting page

- calliope_app/api/models/outputs.py
Adding plotting support to include relevant energy_cap_equals values in the calculation of Max Bounds Context capacity plots
> Add support for energy_cap_equals

- calliope_app/api/calliope_utils.py
Found an issue where if no storage constraints are set on supply+ it doesn't show up in results_storage_cap if nothing is built. Adding code to default a 0 capacity in results_yaml if the loc_tech is missing from the energy/storage capacity file to prevent model errors if this happens
> Fixing issue where techs could be missing

- calliope_app/api/models/outputs.py
Fixing bug with trying to load carrier units for plots in runs that predate carrier units
> Fix carriers plotting issue for old runs

- calliope_app/api/fixtures/admin_run_parameter.json
- calliope_app/requirements.txt
Adding Xpress Python wrapper package and adding option to specify "xpress_direct" to have Pyomo use the direct wrapper instead of ampl
> Adding Xpress python bindings

- calliope_app/api/models/configuration.py
- calliope_app/client/templates/technology_parameters.html
Fixing bug where putting a related_name on carriers broke the model copying code that assumed the default _set to copy model sub-objects
> Fix model copying bug with carriers

- calliope_app/requirements.txt
```bash
calliope-short-worker  | "safe_load()" has been removed, use
calliope-short-worker  |
calliope-short-worker  |   yaml = YAML(typ='safe', pure=True)
calliope-short-worker  |   yaml.load(...)
calliope-short-worker  |
calliope-short-worker  | instead of file "/usr/local/lib/python3.8/site-packages/calliope/core/attrdict.py", line 47
calliope-short-worker  |
calliope-short-worker  |         result = ruamel_yaml.safe_load(src)
```
Pin `ruamel.yaml == 0.16.0` as a temp solution.
> Pin ruamel yaml == 0.16.0

- calliope_app/client/static/js/main.js
- calliope_app/client/templates/map_container_resizable.html
This is a PR to fix the map legend that was previously interrupted by splitting the scenario tab. The legend for the scenarios tab is currently missing in dev. This PR fixes that, such that when you hover over a node, the map-legend appears in the top left corner as it does in the master branch.
> Fixing map-legend

- calliope_app/client/templates/scenarios.html
The vertical splitter on Scenario page got removed somehow in this PR #159 , added it back.
Code related:
https://github.com/NREL/engage/pull/159/files#diff-21b1f30849ae37170afa74484c029822dfe0d6caa4ee179bf258162be4a31962L175
> engage76-Restore scenario vertical splitter

- docker-compose.yml
After having docker engine updated,
Now it's showing WARN when starting docker-compose at local,
It shows:
WARN[0000] ~/engage/engage-public/docker-compose.yml: `version` is obsolete
Solution:
Remove the top version,
more information, please refer here - https://github.com/jasonacox/Powerwall-Dashboard/issues/453#issuecomment-2008619928
> engage90-Remove informational version of docker compose

- calliope_app/client/templates/scenario_details.html
This makes sure that the scenario description defaults to an empty string rather than none.
vs.
> Scenario description

- calliope_app/compose/Dockerfile
Git is used to install GEOPHIRES-X, no need anymore after the package installation, remove to make image smaller.
> Dockerfile clean up & remove git

- calliope_app/api/calliope_utils.py
Initial commit updating the _yaml_outputs() and apply_gradient() routines to work with the new calliope 0.7 YAML formats and timeseries CSV format
Tested locally with a simple model for both regular and transmission capacity expansion
Various fixes (systemwide constraints, transmission, ect.) have been implemented, but other proposed improvements (retirements, multiyear params) have not been implemented yet
Assumes a proposed change to add an optional links key for transmission is enacted
Group constraints are left un-implemented and will be updated with group constraint work
> Updating YAML outputs and gradient for v07
