NREL/engage

calliope_app/api/views/engage.py

Temporary fix to prevent insertion of html scripts into user first/last names

Temporary fix for html tags in names

---

calliope_app/api/views/outputs.py

Added yearly parameter support by adding "_YYYY" to any parameter column on the tech or loc_tech uploads

Added support for yearly parameters to bulk data

---

calliope_app/api/views/outputs.py
calliope_app/client/static/js/model.js

Readding pretty_tag support
Adding support for specifying timeseries by name for non-file timeseries like PVWatts
Fixing bug with location_2 on nodes export

Misc bug fixes

---

calliope_app/api/views/outputs.py

Fixing bug causing errors when making new locations.

Misc bug fix

---

calliope_app/api/views/outputs.py

Added better tag support to imports/exports to handle techs with the same name and different tags
Fixed issue where ids weren't causing loc_techs to be updated

Added better tag support

---

calliope_app/api/calliope_utils.py
calliope_app/api/utils.py

Adding bulk data yaml downloads
Fixing issue with custom user units/constants

Adding bulk data yaml downloads

---

calliope_app/api/models/engage.py
calliope_app/api/tests/test_views/test_configuration.py
calliope_app/api/views/configuration.py
calliope_app/client/static/js/home.js
calliope_app/client/static/js/model.js
calliope_app/client/static/js/settings.js
calliope_app/client/templates/activity.html
calliope_app/client/templates/home_new_model.html
calliope_app/client/templates/share.html

* Sanitize model name and comment inputs, to avoid HTML string with xss.
* In model sharing, reference to user by id, not email address.

Sanitize model names, model comments, and user reference

---

calliope_app/api/calliope_utils.py

Fixing bug where new cost classes introduced duplicate parameter names which we filtered out

Fixing issue with duplicate parameter names

---

calliope_app/client/static/js/run_timeseries.js

Fixing bug causing production/consumption plots to overlap in UI

Fixing overlap bug

---

calliope_app/api/calliope_utils.py

Fixed bug causing crash during output yaml generation if model was infeasible and results files don't exist

Fix bug causing missing file error

---

calliope_app/api/calliope_utils.py
calliope_app/api/models/outputs.py
calliope_app/compose/Dockerfile
calliope_app/requirements.txt

Upgrading dependencies to remove vulnerabilities and upgrading to Calliope version 0.6.8
Fixing plotting bug for runs without storage

Upgrading libraries

---

calliope_app/api/views/outputs.py

Fixing bug with "nan" strings causing errors in the loctechs upload

Fixing "nan" bug in tags

---

calliope_app/api/views/outputs.py

Fixing issue that would result in a blank bulk download for technology tags

Fixing tag/pretty_tag issue with loc_tech download

---

calliope_app/api/calliope_utils.py
calliope_app/api/views/outputs.py

Fixing issue where tech description wasn't in bulk download file
Undoing change to turn "False" values into null and instead setting them back to false

Fixing misc bugs

---

calliope_app/api/calliope_utils.py

Adding storage_cap_equals to results yaml and fixing a bug that would wipe out energy_cap_equals for storage

Adding storage cap to YAML outputs

---

calliope_app/client/static/js/run.js
calliope_app/client/templates/run_dashboard.html

Adding new run build flags to reenable the out of date button new run functionality on the runs tab

Fixing out of date button on runs tab

---

calliope_app/api/calliope_utils.py
calliope_app/api/views/outputs.py

Fixing timeseries copying code to correctly change years and handle leap years
Extending updated timeseries copying code to include timeseries in tech params

Fixing remaining timeseries issues

---

calliope_app/api/tasks.py
calliope_app/api/views/outputs.py
calliope_app/client/static/js/add_run.js
calliope_app/client/templates/add_run.html

Fixing gradient logging to account for infeasible runs in a gradient chain
Adding run notes to add_run page to fill in description on run creation (including gradient runs)

Fixing logging and adding notes field to add_run

---

calliope_app/calliope_app/settings/base.py
calliope_app/geophires/apps.py
calliope_app/geophires/configs/binary_subcritical.txt
calliope_app/geophires/configs/binary_supercritical.txt
calliope_app/geophires/configs/chp_topping.txt
calliope_app/geophires/configs/direct_use.txt
calliope_app/geophires/configs/flash_double.txt
calliope_app/geophires/configs/flash_single.txt
calliope_app/geophires/tasks.py
calliope_app/geophires/tests.py
calliope_app/geophires/v2.py
calliope_app/template/geophires.py

About this PR
* Integrate Geophires function into Engage - https://github.com/NREL/GEOPHIRES-v2.
* Setup Celery task to run Geophires jobs, and update job meta during the process. 
* Connect Geophires run with Template form inputs (no test yet, can test after merged into `templates-feature` branch).
TODO:
* Determine Geophires steps between min and max.
* Specify `plant` value.

Init geophires backend

---

calliope_app/geophires/v2.py
calliope_app/template/geophires.py

What's in this PR?
* Fix geophires mapping about lifetime, efficiency, and interest_rate.

fix geophires mapping

---

calliope_app/api/calliope_utils.py

Fixing issue where when trying to copy timeseries from a non-leap year to a leap year there would be an error trying to fill while reindexing dataframe

Fixing indexing issue with Feb 29th reindexing

---

calliope_app/api/models/outputs.py

Fixing issue plotting old runs where it assumed carriers.yaml existed

Fixing issue plotting old runs

---

calliope_app/client/templates/technology_parameters.html

Fixing a bug where fixing the carrier dropdowns in the parameter table broke the choices dropdowns. Also applying the fixes to multiyear dropdown parameters

Fixing bug with carrier dropdowns and choice dropdowns

---

calliope_app/api/views/outputs.py
calliope_app/requirements.txt

Making sure bulk data correctly grabs and substitutes the units of carriers when doing unit conversion on parameters

Fixing issues with bulk data and new units for carriers

---

calliope_app/client/static/js/scenarios.js

Refactored group constraints list to be a dictionary with constraint dimensions specified rather than hardcoded with indices
Added new reserve margin group constraints

Refactoring group constraint list and adding reserve margins

---

calliope_app/api/models/outputs.py

A quick one fix, but not sure why it re-formaatted the whole script. This is a PR merged into dev in private repo.

Bugfix for run tab issue

---

calliope_app/api/utils.py
calliope_app/client/static/js/units.js

Adding TOR aka ton (refrigeration) as a unit

Adding TOR as a unit

---

calliope_app/client/templates/share.html

Under "Select a user" on model share page, this PR enables to show user organization.

engage77-Show user organization in list

---

calliope_app/api/urls.py
calliope_app/api/views/configuration.py
calliope_app/client/views/configuration.py
calliope_app/client/views/engage.py
calliope_app/client/views/outputs.py

Ratelimit2

---

calliope_app/client/static/js/scenarios.js

Minor fix to prevent techs_lhs from being set if techs is

Minor fix to prevent techs_lhs from being set if techs is

---

calliope_app/api/fixtures/admin_run_parameter.json
calliope_app/api/fixtures/sample_scenario_param.json
calliope_app/calliope-files/backend/pyomo/model.py
calliope_app/compose/Dockerfile
docs/_sources/release-notes.rst.txt
docs/index.html
docs/optimization-solvers.html
docs/sources/optimization-solvers.rst
docs/sources/resources/calliope-063/example_models/national_scale/model.yaml
docs/sources/resources/calliope-063/example_models/urban_scale/model.yaml

This PR removes the GLPK solver and replaces it with the CBC solver.

Solver -- Replacing GLPK With CBC

---

calliope_app/api/fixtures/admin_run_parameter.json

fix fixture

---

calliope_app/account/urls.py
calliope_app/calliope_app/settings/local.py
calliope_app/calliope_app/settings/prod.py
calliope_app/calliope_app/settings/test.py
calliope_app/requirements.txt
calliope_app/template/urls.py

Upgrade Django to 4.2.x (LTS version).

Django upgrade to 4.2.15

---

calliope_app/client/static/css/main.css
calliope_app/client/templates/base.html
calliope_app/client/templates/registration/login.html
calliope_app/client/templates/registration/registration.html
docs/_sources/developer-guide.rst.txt
docs/developer-guide.html
docs/engage-user-guide.html
docs/sources/developer-guide.rst

Draft documentation page for now just testing to make sure I know how to deploy the git documentation for monday

Engage 134 calliope 7 documentation 

---

calliope_app/api/calliope_utils.py
calliope_app/api/fixtures/admin_group_constraint.json
calliope_app/api/models/outputs.py
calliope_app/client/static/js/scenarios.js
docs/sources/resources/calliope-063/example_models/urban_scale/model_config/techs.yaml

Updating group constraints fixtures
Misc fixes/updates to the group constraint UI
Adjusting transmission to use the new 'templates' renamed from 'tech_group'

Updating group_constraints fixtures

---

calliope_app/client/templates/add_technology.html

Disabled the option to build new conversion_plus or supply_plus techs in the catalog for now

Disabling conversion and supply plus for now

---

calliope_app/client/static/js/loc_techs.js
calliope_app/template/fixtures/admin_template_type_loc_tech_params.json
calliope_app/template/fixtures/admin_template_type_tech_params.json

Engage 135 template types
